#Basic request call to gather raw html from the website

In [ ]:
import requests
url="https://books.toscrape.com/index.html"
response=requests.get(url)
print(response.text)

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="24th Jun 2016 09:29" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


            <link rel="shortcut icon" href="static/oscar/favicon.ico" />






        <link rel="stylesheet" type="text/css" href="static/oscar/css/styles.css" />

    <link rel="stylesheet" href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" />
    <link rel="stylesheet" type="text/css" href="static/oscar/css/datetimepicker.css" />












    </head>

    <body id="default" class="default">




    <header class="header container-fluid">
        <div class="page_inner">
            <div class="row">
                <div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>


            </div>
        </div>
    </header>



<div class="container-fluid page">
    <div class="page_inner">

    <ul class="breadcrumb">
        <li>
            <a href="index.html">Home</a>
        </li>
        <li class="active">All products</li>
    </ul>

        <div class="row">

            <aside class="sidebar col-sm-4 col-md-3">

                <div id="promotions_left">

                </div>




        <div class="side_categories">
            <ul class="nav nav-list">

                    <li>
                        <a href="catalogue/category/books_1/index.html">

                                Books

                        </a>

                        <ul>


                    <li>
                        <a href="catalogue/category/books/travel_2/index.html">

                                Travel

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/mystery_3/index.html">

                                Mystery

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/historical-fiction_4/index.html">

                                Historical Fiction

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/sequential-art_5/index.html">

                                Sequential Art

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/classics_6/index.html">

                                Classics

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/philosophy_7/index.html">

                                Philosophy

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/romance_8/index.html">

                                Romance

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/womens-fiction_9/index.html">

                                Womens Fiction

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/fiction_10/index.html">

                                Fiction

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/childrens_11/index.html">

                                Childrens

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/religion_12/index.html">

                                Religion

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/nonfiction_13/index.html">

                                Nonfiction

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/music_14/index.html">

                                Music

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/default_15/index.html">

                                Default

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/science-fiction_16/index.html">

                                Science Fiction

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/sports-and-games_17/index.html">

                                Sports and Games

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/add-a-comment_18/index.html">

                                Add a comment

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/fantasy_19/index.html">

                                Fantasy

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/new-adult_20/index.html">

                                New Adult

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/young-adult_21/index.html">

                                Young Adult

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/science_22/index.html">

                                Science

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/poetry_23/index.html">

                                Poetry

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/paranormal_24/index.html">

                                Paranormal

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/art_25/index.html">

                                Art

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/psychology_26/index.html">

                                Psychology

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/autobiography_27/index.html">

                                Autobiography

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/parenting_28/index.html">

                                Parenting

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/adult-fiction_29/index.html">

                                Adult Fiction

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/humor_30/index.html">

                                Humor

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/horror_31/index.html">

                                Horror

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/history_32/index.html">

                                History

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/food-and-drink_33/index.html">

                                Food and Drink

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/christian-fiction_34/index.html">

                                Christian Fiction

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/business_35/index.html">

                                Business

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/biography_36/index.html">

                                Biography

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/thriller_37/index.html">

                                Thriller

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/contemporary_38/index.html">

                                Contemporary

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/spirituality_39/index.html">

                                Spirituality

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/academic_40/index.html">

                                Academic

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/self-help_41/index.html">

                                Self Help

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/historical_42/index.html">

                                Historical

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/christian_43/index.html">

                                Christian

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/suspense_44/index.html">

                                Suspense

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/short-stories_45/index.html">

                                Short Stories

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/novels_46/index.html">

                                Novels

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/health_47/index.html">

                                Health

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/politics_48/index.html">

                                Politics

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/cultural_49/index.html">

                                Cultural

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/erotica_50/index.html">

                                Erotica

                        </a>

                        </li>


                    <li>
                        <a href="catalogue/category/books/crime_51/index.html">

                                Crime

                        </a>

                        </li>

                            </ul></li>


            </ul>
        </div>



            </aside>

            <div class="col-sm-8 col-md-9">

                <div class="page-header action">
                    <h1>All products</h1>
                </div>






<div id="messages">

</div>


                <div id="promotions">

                </div>


    <form method="get" class="form-horizontal">

        <div style="display:none">


        </div>




                    <strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.




    </form>

        <section>
            <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>

            <div>
                <ol class="row">

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="catalogue/a-light-in-the-attic_1000/index.html"><img src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg" alt="A Light in the Attic" class="thumbnail"></a>


            </div>




                <p class="star-rating Three">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£51.77</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="catalogue/tipping-the-velvet_999/index.html"><img src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg" alt="Tipping the Velvet" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>



            <div class="product_price">








        <p class="price_color">Â£53.74</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="catalogue/soumission_998/index.html"><img src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg" alt="Soumission" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>



            <div class="product_price">








        <p class="price_color">Â£50.10</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="catalogue/sharp-objects_997/index.html"><img src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg" alt="Sharp Objects" class="thumbnail"></a>


            </div>




                <p class="star-rating Four">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>



            <div class="product_price">








        <p class="price_color">Â£47.82</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg" alt="Sapiens: A Brief History of Humankind" class="thumbnail"></a>


            </div>




                <p class="star-rating Five">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£54.23</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">



In [ ]:
import pandas as pd

In [ ]:
from bs4 import BeautifulSoup

#seperating articles i.e books from other irrelavent tasks

In [ ]:
soup=BeautifulSoup(response.text)
articles=soup.find_all("article", class_="product_pod")

#planning on using these urls to automate the scraping process instead of manual url injection

In [ ]:
side_categories=soup.find("div",class_="side_categories")
side_categories

<div class="side_categories">
<ul class="nav nav-list">
<li>
<a href="catalogue/category/books_1/index.html">

                                Books

                        </a>
<ul>
<li>
<a href="catalogue/category/books/travel_2/index.html">

                                Travel

                        </a>
</li>
<li>
<a href="catalogue/category/books/mystery_3/index.html">

                                Mystery

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical-fiction_4/index.html">

                                Historical Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sequential-art_5/index.html">

                                Sequential Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/classics_6/index.html">

                                Classics

                        </a>
</li>
<li>
<a href="catalogue/category/books/philosophy_7/index.html">

                                Philosophy

                        </a>
</li>
<li>
<a href="catalogue/category/books/romance_8/index.html">

                                Romance

                        </a>
</li>
<li>
<a href="catalogue/category/books/womens-fiction_9/index.html">

                                Womens Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/fiction_10/index.html">

                                Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/childrens_11/index.html">

                                Childrens

                        </a>
</li>
<li>
<a href="catalogue/category/books/religion_12/index.html">

                                Religion

                        </a>
</li>
<li>
<a href="catalogue/category/books/nonfiction_13/index.html">

                                Nonfiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/music_14/index.html">

                                Music

                        </a>
</li>
<li>
<a href="catalogue/category/books/default_15/index.html">

                                Default

                        </a>
</li>
<li>
<a href="catalogue/category/books/science-fiction_16/index.html">

                                Science Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/sports-and-games_17/index.html">

                                Sports and Games

                        </a>
</li>
<li>
<a href="catalogue/category/books/add-a-comment_18/index.html">

                                Add a comment

                        </a>
</li>
<li>
<a href="catalogue/category/books/fantasy_19/index.html">

                                Fantasy

                        </a>
</li>
<li>
<a href="catalogue/category/books/new-adult_20/index.html">

                                New Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/young-adult_21/index.html">

                                Young Adult

                        </a>
</li>
<li>
<a href="catalogue/category/books/science_22/index.html">

                                Science

                        </a>
</li>
<li>
<a href="catalogue/category/books/poetry_23/index.html">

                                Poetry

                        </a>
</li>
<li>
<a href="catalogue/category/books/paranormal_24/index.html">

                                Paranormal

                        </a>
</li>
<li>
<a href="catalogue/category/books/art_25/index.html">

                                Art

                        </a>
</li>
<li>
<a href="catalogue/category/books/psychology_26/index.html">

                                Psychology

                        </a>
</li>
<li>
<a href="catalogue/category/books/autobiography_27/index.html">

                                Autobiography

                        </a>
</li>
<li>
<a href="catalogue/category/books/parenting_28/index.html">

                                Parenting

                        </a>
</li>
<li>
<a href="catalogue/category/books/adult-fiction_29/index.html">

                                Adult Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/humor_30/index.html">

                                Humor

                        </a>
</li>
<li>
<a href="catalogue/category/books/horror_31/index.html">

                                Horror

                        </a>
</li>
<li>
<a href="catalogue/category/books/history_32/index.html">

                                History

                        </a>
</li>
<li>
<a href="catalogue/category/books/food-and-drink_33/index.html">

                                Food and Drink

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian-fiction_34/index.html">

                                Christian Fiction

                        </a>
</li>
<li>
<a href="catalogue/category/books/business_35/index.html">

                                Business

                        </a>
</li>
<li>
<a href="catalogue/category/books/biography_36/index.html">

                                Biography

                        </a>
</li>
<li>
<a href="catalogue/category/books/thriller_37/index.html">

                                Thriller

                        </a>
</li>
<li>
<a href="catalogue/category/books/contemporary_38/index.html">

                                Contemporary

                        </a>
</li>
<li>
<a href="catalogue/category/books/spirituality_39/index.html">

                                Spirituality

                        </a>
</li>
<li>
<a href="catalogue/category/books/academic_40/index.html">

                                Academic

                        </a>
</li>
<li>
<a href="catalogue/category/books/self-help_41/index.html">

                                Self Help

                        </a>
</li>
<li>
<a href="catalogue/category/books/historical_42/index.html">

                                Historical

                        </a>
</li>
<li>
<a href="catalogue/category/books/christian_43/index.html">

                                Christian

                        </a>
</li>
<li>
<a href="catalogue/category/books/suspense_44/index.html">

                                Suspense

                        </a>
</li>
<li>
<a href="catalogue/category/books/short-stories_45/index.html">

                                Short Stories

                        </a>
</li>
<li>
<a href="catalogue/category/books/novels_46/index.html">

                                Novels

                        </a>
</li>
<li>
<a href="catalogue/category/books/health_47/index.html">

                                Health

                        </a>
</li>
<li>
<a href="catalogue/category/books/politics_48/index.html">

                                Politics

                        </a>
</li>
<li>
<a href="catalogue/category/books/cultural_49/index.html">

                                Cultural

                        </a>
</li>
<li>
<a href="catalogue/category/books/erotica_50/index.html">

                                Erotica

                        </a>
</li>
<li>
<a href="catalogue/category/books/crime_51/index.html">

                                Crime

                        </a>
</li>
</ul></li>
</ul>
</div>

In [ ]:
side_categories=soup.find("div",class_="side_categories")
categories={}
for a_tag in side_categories.find_all("a"):
    category_link = a_tag["href"]
    category_name = a_tag.text.strip()  # .strip() cleans up the extra spaces/newlines
    categories[category_name]=category_link

In [ ]:

categories.pop('Books', None)

'catalogue/category/books_1/index.html'

In [ ]:
categories

{'Travel': 'catalogue/category/books/travel_2/index.html',
 'Mystery': 'catalogue/category/books/mystery_3/index.html',
 'Historical Fiction': 'catalogue/category/books/historical-fiction_4/index.html',
 'Sequential Art': 'catalogue/category/books/sequential-art_5/index.html',
 'Classics': 'catalogue/category/books/classics_6/index.html',
 'Philosophy': 'catalogue/category/books/philosophy_7/index.html',
 'Romance': 'catalogue/category/books/romance_8/index.html',
 'Womens Fiction': 'catalogue/category/books/womens-fiction_9/index.html',
 'Fiction': 'catalogue/category/books/fiction_10/index.html',
 'Childrens': 'catalogue/category/books/childrens_11/index.html',
 'Religion': 'catalogue/category/books/religion_12/index.html',
 'Nonfiction': 'catalogue/category/books/nonfiction_13/index.html',
 'Music': 'catalogue/category/books/music_14/index.html',
 'Default': 'catalogue/category/books/default_15/index.html',
 'Science Fiction': 'catalogue/category/books/science-fiction_16/index.html',
 'Sports and Games': 'catalogue/category/books/sports-and-games_17/index.html',
 'Add a comment': 'catalogue/category/books/add-a-comment_18/index.html',
 'Fantasy': 'catalogue/category/books/fantasy_19/index.html',
 'New Adult': 'catalogue/category/books/new-adult_20/index.html',
 'Young Adult': 'catalogue/category/books/young-adult_21/index.html',
 'Science': 'catalogue/category/books/science_22/index.html',
 'Poetry': 'catalogue/category/books/poetry_23/index.html',
 'Paranormal': 'catalogue/category/books/paranormal_24/index.html',
 'Art': 'catalogue/category/books/art_25/index.html',
 'Psychology': 'catalogue/category/books/psychology_26/index.html',
 'Autobiography': 'catalogue/category/books/autobiography_27/index.html',
 'Parenting': 'catalogue/category/books/parenting_28/index.html',
 'Adult Fiction': 'catalogue/category/books/adult-fiction_29/index.html',
 'Humor': 'catalogue/category/books/humor_30/index.html',
 'Horror': 'catalogue/category/books/horror_31/index.html',
 'History': 'catalogue/category/books/history_32/index.html',
 'Food and Drink': 'catalogue/category/books/food-and-drink_33/index.html',
 'Christian Fiction': 'catalogue/category/books/christian-fiction_34/index.html',
 'Business': 'catalogue/category/books/business_35/index.html',
 'Biography': 'catalogue/category/books/biography_36/index.html',
 'Thriller': 'catalogue/category/books/thriller_37/index.html',
 'Contemporary': 'catalogue/category/books/contemporary_38/index.html',
 'Spirituality': 'catalogue/category/books/spirituality_39/index.html',
 'Academic': 'catalogue/category/books/academic_40/index.html',
 'Self Help': 'catalogue/category/books/self-help_41/index.html',
 'Historical': 'catalogue/category/books/historical_42/index.html',
 'Christian': 'catalogue/category/books/christian_43/index.html',
 'Suspense': 'catalogue/category/books/suspense_44/index.html',
 'Short Stories': 'catalogue/category/books/short-stories_45/index.html',
 'Novels': 'catalogue/category/books/novels_46/index.html',
 'Health': 'catalogue/category/books/health_47/index.html',
 'Politics': 'catalogue/category/books/politics_48/index.html',
 'Cultural': 'catalogue/category/books/cultural_49/index.html',
 'Erotica': 'catalogue/category/books/erotica_50/index.html',
 'Crime': 'catalogue/category/books/crime_51/index.html'}

In [ ]:
articles

[<article class="product_pod">
 <div class="image_container">
 <a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.74</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
 <div class="product_price">
 <p class="price_color">Â£50.10</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
 <div class="product_price">
 <p class="price_color">Â£47.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£54.23</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.65</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.34</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.93</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.60</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.15</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£13.99</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
 <div class="product_price">
 <p class="price_color">Â£20.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.46</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£35.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html"><img alt="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991" class="thumbnail" src="media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£57.25</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/olio_984/index.html"><img alt="Olio" class="thumbnail" src="media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
 <div class="product_price">
 <p class="price_color">Â£23.88</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£37.59</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.33</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
 <div class="product_price">
 <p class="price_color">Â£45.17</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>]

#Practicing how to parse the raww html with find_all and select

In [ ]:
titles=soup.find_all("h3")
title=[]
for titl in titles:
    a_tag=titl.find("a")

    if a_tag:
        titl=a_tag["title"]
        title.append(titl)
print(title)

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas"]

In [ ]:
ratings=soup.find_all("p",class_="star-rating")
all_ratings=[]
for tag in ratings:
    rating_word = tag["class"][1]
    all_ratings.append(rating_word)
print(all_ratings)

['Three', 'One', 'One', 'Four', 'Five', 'One', 'Four', 'Three', 'Four', 'One', 'Two', 'Four', 'Five', 'Five', 'Five', 'Three', 'One', 'One', 'Two', 'Two']

In [ ]:

title = [a["title"] for a in soup.select("h3 > a[title]")]
print(title)

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas"]

In [ ]:
price_stock=soup.find_all("div",class_="product_price")
price=[]
stock=[]
for tag in price_stock:
    pri=tag.find("p",class_="price_color").text
    sto=tag.find("p",class_="instock availability").text.strip()
    price.append(pri)
    stock.append(sto)
print(price)
print(stock)

['Â£51.77', 'Â£53.74', 'Â£50.10', 'Â£47.82', 'Â£54.23', 'Â£22.65', 'Â£33.34', 'Â£17.93', 'Â£22.60', 'Â£52.15', 'Â£13.99', 'Â£20.66', 'Â£17.46', 'Â£52.29', 'Â£35.02', 'Â£57.25', 'Â£23.88', 'Â£37.59', 'Â£51.33', 'Â£45.17']
['In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock', 'In stock']

#Generatings recordss of books for reliablity

In [ ]:
 '''<article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
 <div class="product_price">
 <p class="price_color">Â£47.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
# </article>,'''

'<article class="product_pod">\n<div class="image_container">\n<a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>\n</div>\n<p class="star-rating Four">\n<i class="icon-star"></i>\n<i class="icon-star"></i>\n<i class="icon-star"></i>\n<i class="icon-star"></i>\n<i class="icon-star"></i>\n</p>\n<h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>\n<div class="product_price">\n<p class="price_color">Â£47.82</p>\n<p class="instock availability">\n<i class="icon-ok"></i>\n\n        In stock\n\n</p>\n<form>\n<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>\n</form>\n</div>\n# </article>,'

In [ ]:
categories

{'Travel': 'catalogue/category/books/travel_2/index.html',
 'Mystery': 'catalogue/category/books/mystery_3/index.html',
 'Historical Fiction': 'catalogue/category/books/historical-fiction_4/index.html',
 'Sequential Art': 'catalogue/category/books/sequential-art_5/index.html',
 'Classics': 'catalogue/category/books/classics_6/index.html',
 'Philosophy': 'catalogue/category/books/philosophy_7/index.html',
 'Romance': 'catalogue/category/books/romance_8/index.html',
 'Womens Fiction': 'catalogue/category/books/womens-fiction_9/index.html',
 'Fiction': 'catalogue/category/books/fiction_10/index.html',
 'Childrens': 'catalogue/category/books/childrens_11/index.html',
 'Religion': 'catalogue/category/books/religion_12/index.html',
 'Nonfiction': 'catalogue/category/books/nonfiction_13/index.html',
 'Music': 'catalogue/category/books/music_14/index.html',
 'Default': 'catalogue/category/books/default_15/index.html',
 'Science Fiction': 'catalogue/category/books/science-fiction_16/index.html',
 'Sports and Games': 'catalogue/category/books/sports-and-games_17/index.html',
 'Add a comment': 'catalogue/category/books/add-a-comment_18/index.html',
 'Fantasy': 'catalogue/category/books/fantasy_19/index.html',
 'New Adult': 'catalogue/category/books/new-adult_20/index.html',
 'Young Adult': 'catalogue/category/books/young-adult_21/index.html',
 'Science': 'catalogue/category/books/science_22/index.html',
 'Poetry': 'catalogue/category/books/poetry_23/index.html',
 'Paranormal': 'catalogue/category/books/paranormal_24/index.html',
 'Art': 'catalogue/category/books/art_25/index.html',
 'Psychology': 'catalogue/category/books/psychology_26/index.html',
 'Autobiography': 'catalogue/category/books/autobiography_27/index.html',
 'Parenting': 'catalogue/category/books/parenting_28/index.html',
 'Adult Fiction': 'catalogue/category/books/adult-fiction_29/index.html',
 'Humor': 'catalogue/category/books/humor_30/index.html',
 'Horror': 'catalogue/category/books/horror_31/index.html',
 'History': 'catalogue/category/books/history_32/index.html',
 'Food and Drink': 'catalogue/category/books/food-and-drink_33/index.html',
 'Christian Fiction': 'catalogue/category/books/christian-fiction_34/index.html',
 'Business': 'catalogue/category/books/business_35/index.html',
 'Biography': 'catalogue/category/books/biography_36/index.html',
 'Thriller': 'catalogue/category/books/thriller_37/index.html',
 'Contemporary': 'catalogue/category/books/contemporary_38/index.html',
 'Spirituality': 'catalogue/category/books/spirituality_39/index.html',
 'Academic': 'catalogue/category/books/academic_40/index.html',
 'Self Help': 'catalogue/category/books/self-help_41/index.html',
 'Historical': 'catalogue/category/books/historical_42/index.html',
 'Christian': 'catalogue/category/books/christian_43/index.html',
 'Suspense': 'catalogue/category/books/suspense_44/index.html',
 'Short Stories': 'catalogue/category/books/short-stories_45/index.html',
 'Novels': 'catalogue/category/books/novels_46/index.html',
 'Health': 'catalogue/category/books/health_47/index.html',
 'Politics': 'catalogue/category/books/politics_48/index.html',
 'Cultural': 'catalogue/category/books/cultural_49/index.html',
 'Erotica': 'catalogue/category/books/erotica_50/index.html',
 'Crime': 'catalogue/category/books/crime_51/index.html'}

In [ ]:
test={'Travel': 'catalogue/category/books/travel_2/index.html'}

#Automating url injection and scraping data from different urls.

In [ ]:
master=[]
tag="https://books.toscrape.com/"
for category,last in categories.items():
    url=tag+last
    print(url)
    response=requests.get(url)
    soup=BeautifulSoup(response.text)
    articles=soup.find_all("article", class_="product_pod")
    for article in articles:
        title=article.select_one("h3 > a[title]").get("title")
        price=article.find("p",class_="price_color").text
        rating=article.find("p",class_="star-rating")["class"][1]
        availability=article.find("p",class_="instock availability").text.strip()
        record=[title,price,rating,availability,category]
        master.append(record)

https://books.toscrape.com/catalogue/category/books/travel_2/index.html
https://books.toscrape.com/catalogue/category/books/mystery_3/index.html
https://books.toscrape.com/catalogue/category/books/historical-fiction_4/index.html
https://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html
https://books.toscrape.com/catalogue/category/books/classics_6/index.html
https://books.toscrape.com/catalogue/category/books/philosophy_7/index.html
https://books.toscrape.com/catalogue/category/books/romance_8/index.html
https://books.toscrape.com/catalogue/category/books/womens-fiction_9/index.html
https://books.toscrape.com/catalogue/category/books/fiction_10/index.html
https://books.toscrape.com/catalogue/category/books/childrens_11/index.html
https://books.toscrape.com/catalogue/category/books/religion_12/index.html
https://books.toscrape.com/catalogue/category/books/nonfiction_13/index.html
https://books.toscrape.com/catalogue/category/books/music_14/index.html
https://books.toscrape.com/catalogue/category/books/default_15/index.html
https://books.toscrape.com/catalogue/category/books/science-fiction_16/index.html
https://books.toscrape.com/catalogue/category/books/sports-and-games_17/index.html
https://books.toscrape.com/catalogue/category/books/add-a-comment_18/index.html
https://books.toscrape.com/catalogue/category/books/fantasy_19/index.html
https://books.toscrape.com/catalogue/category/books/new-adult_20/index.html
https://books.toscrape.com/catalogue/category/books/young-adult_21/index.html
https://books.toscrape.com/catalogue/category/books/science_22/index.html
https://books.toscrape.com/catalogue/category/books/poetry_23/index.html
https://books.toscrape.com/catalogue/category/books/paranormal_24/index.html
https://books.toscrape.com/catalogue/category/books/art_25/index.html
https://books.toscrape.com/catalogue/category/books/psychology_26/index.html
https://books.toscrape.com/catalogue/category/books/autobiography_27/index.html
https://books.toscrape.com/catalogue/category/books/parenting_28/index.html
https://books.toscrape.com/catalogue/category/books/adult-fiction_29/index.html
https://books.toscrape.com/catalogue/category/books/humor_30/index.html
https://books.toscrape.com/catalogue/category/books/horror_31/index.html
https://books.toscrape.com/catalogue/category/books/history_32/index.html
https://books.toscrape.com/catalogue/category/books/food-and-drink_33/index.html
https://books.toscrape.com/catalogue/category/books/christian-fiction_34/index.html
https://books.toscrape.com/catalogue/category/books/business_35/index.html
https://books.toscrape.com/catalogue/category/books/biography_36/index.html
https://books.toscrape.com/catalogue/category/books/thriller_37/index.html
https://books.toscrape.com/catalogue/category/books/contemporary_38/index.html
https://books.toscrape.com/catalogue/category/books/spirituality_39/index.html
https://books.toscrape.com/catalogue/category/books/academic_40/index.html
https://books.toscrape.com/catalogue/category/books/self-help_41/index.html
https://books.toscrape.com/catalogue/category/books/historical_42/index.html
https://books.toscrape.com/catalogue/category/books/christian_43/index.html
https://books.toscrape.com/catalogue/category/books/suspense_44/index.html
https://books.toscrape.com/catalogue/category/books/short-stories_45/index.html
https://books.toscrape.com/catalogue/category/books/novels_46/index.html
https://books.toscrape.com/catalogue/category/books/health_47/index.html
https://books.toscrape.com/catalogue/category/books/politics_48/index.html
https://books.toscrape.com/catalogue/category/books/cultural_49/index.html
https://books.toscrape.com/catalogue/category/books/erotica_50/index.html
https://books.toscrape.com/catalogue/category/books/crime_51/index.html

In [ ]:
master[:10]

[["It's Only the Himalayas", 'Â£45.17', 'Two', 'In stock', 'Travel'],
 ['Full Moon over Noahâ\x80\x99s Ark: An Odyssey to Mount Ararat and Beyond',
  'Â£49.43',
  'Four',
  'In stock',
  'Travel'],
 ['See America: A Celebration of Our National Parks & Treasured Sites',
  'Â£48.87',
  'Three',
  'In stock',
  'Travel'],
 ['Vagabonding: An Uncommon Guide to the Art of Long-Term World Travel',
  'Â£36.94',
  'Two',
  'In stock',
  'Travel'],
 ['Under the Tuscan Sun', 'Â£37.33', 'Three', 'In stock', 'Travel'],
 ['A Summer In Europe', 'Â£44.34', 'Two', 'In stock', 'Travel'],
 ['The Great Railway Bazaar', 'Â£30.54', 'One', 'In stock', 'Travel'],
 ['A Year in Provence (Provence #1)', 'Â£56.88', 'Four', 'In stock', 'Travel'],
 ['The Road to Little Dribbling: Adventures of an American in Britain (Notes From a Small Island #2)',
  'Â£23.21',
  'One',
  'In stock',
  'Travel'],
 ['Neither Here nor There: Travels in Europe',
  'Â£38.95',
  'Three',
  'In stock',
  'Travel']]

#Converting lists into DataFrame

In [ ]:
df=pd.DataFrame(master,columns=["title","price_gbp","rating","in_stock","category"])
df

,title,price_gbp,rating,in_stock,category
0,It's Only the Himalayas,Â£45.17,Two,In stock,Travel
1,Full Moon over Noahâs Ark: An Odyssey to Mou...,Â£49.43,Four,In stock,Travel
2,See America: A Celebration of Our National Par...,Â£48.87,Three,In stock,Travel
3,Vagabonding: An Uncommon Guide to the Art of L...,Â£36.94,Two,In stock,Travel
4,Under the Tuscan Sun,Â£37.33,Three,In stock,Travel
...,...,...,...,...,...
512,Why the Right Went Wrong: Conservatism--From G...,Â£52.65,Four,In stock,Politics
513,Equal Is Unfair: America's Misguided Fight Aga...,Â£56.86,One,In stock,Politics
514,Amid the Chaos,Â£36.58,One,In stock,Cultural
515,Dark Notes,Â£19.19,Five,In stock,Erotica
516,The Long Shadow of Small Ghosts: Murder and Me...,Â£10.97,One,In stock,Crime

#Data Cleaning

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      517 non-null    object
 1   price_gbp  517 non-null    object
 2   rating     517 non-null    object
 3   in_stock   517 non-null    object
 4   category   517 non-null    object
dtypes: object(5)
memory usage: 20.3+ KB

In [ ]:
df['price_gbp']=df['price_gbp'].str.replace("Â£","")
df['price_gbp']=pd.to_numeric(df['price_gbp'],errors='coerce')
df['price_gbp']

0      45.17
1      49.43
2      48.87
3      36.94
4      37.33
       ...
512    52.65
513    56.86
514    36.58
515    19.19
516    10.97
Name: price_gbp, Length: 517, dtype: float64

In [ ]:
df['in_stock'].value_counts()

in_stock
In stock    517
Name: count, dtype: int64

In [ ]:
df["in_stock"] = df["in_stock"].map(
    lambda x: True if x == "In stock" else False
)

In [ ]:
df['in_stock']

0      True
1      True
2      True
3      True
4      True
       ...
512    True
513    True
514    True
515    True
516    True
Name: in_stock, Length: 517, dtype: bool

In [ ]:
mapping_dict={
    "One":1,
    "Two":2,
    "Three":3,
    "Four":4,
    "Five":5
}

In [ ]:
df['rating'] = pd.to_numeric(df['rating'].map(mapping_dict), errors='coerce')

In [ ]:
df

,title,price_gbp,rating,in_stock,category
0,It's Only the Himalayas,45.17,2,True,Travel
1,Full Moon over Noahâs Ark: An Odyssey to Mou...,49.43,4,True,Travel
2,See America: A Celebration of Our National Par...,48.87,3,True,Travel
3,Vagabonding: An Uncommon Guide to the Art of L...,36.94,2,True,Travel
4,Under the Tuscan Sun,37.33,3,True,Travel
...,...,...,...,...,...
512,Why the Right Went Wrong: Conservatism--From G...,52.65,4,True,Politics
513,Equal Is Unfair: America's Misguided Fight Aga...,56.86,1,True,Politics
514,Amid the Chaos,36.58,1,True,Cultural
515,Dark Notes,19.19,5,True,Erotica
516,The Long Shadow of Small Ghosts: Murder and Me...,10.97,1,True,Crime

In [ ]:
df['rating'].value_counts()

rating
1    122
2    105
5    104
3     98
4     88
Name: count, dtype: int64

In [ ]:
df.describe()

        price_gbp      rating
count  517.000000  517.000000
mean    35.315068    2.897485
std     14.341524    1.454455
min     10.010000    1.000000
25%     22.540000    2.000000
50%     36.260000    3.000000
75%     48.190000    4.000000
max     59.990000    5.000000

In [ ]:
df['price_inr']=df['price_gbp']*105.50

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      517 non-null    object
 1   price_gbp  517 non-null    float64
 2   rating     517 non-null    int64
 3   in_stock   517 non-null    bool
 4   category   517 non-null    object
 5   price_inr  517 non-null    float64
dtypes: bool(1), float64(2), int64(1), object(2)
memory usage: 20.8+ KB

In [ ]:
df['category'].value_counts()

category
Mystery               20
Historical Fiction    20
Fantasy               20
Sequential Art        20
Fiction               20
Romance               20
Childrens             20
Add a comment         20
Default               20
Nonfiction            20
Food and Drink        20
Young Adult           20
Classics              19
Poetry                19
History               18
Womens Fiction        17
Horror                17
Science Fiction       16
Science               14
Music                 13
Business              12
Travel                11
Philosophy            11
Thriller              11
Humor                 10
Autobiography          9
Art                    8
Religion               7
Psychology             7
Christian Fiction      6
Spirituality           6
New Adult              6
Sports and Games       5
Biography              5
Self Help              5
Health                 4
Politics               3
Contemporary           3
Christian              3
Historical             2
Paranormal             1
Parenting              1
Adult Fiction          1
Academic               1
Short Stories          1
Suspense               1
Novels                 1
Cultural               1
Erotica                1
Crime                  1
Name: count, dtype: int64

In [ ]:
df.dropna()

,title,price_gbp,rating,in_stock,category,price_inr
0,It's Only the Himalayas,45.17,2,True,Travel,4765.435
1,Full Moon over Noahâs Ark: An Odyssey to Mou...,49.43,4,True,Travel,5214.865
2,See America: A Celebration of Our National Par...,48.87,3,True,Travel,5155.785
3,Vagabonding: An Uncommon Guide to the Art of L...,36.94,2,True,Travel,3897.170
4,Under the Tuscan Sun,37.33,3,True,Travel,3938.315
...,...,...,...,...,...,...
512,Why the Right Went Wrong: Conservatism--From G...,52.65,4,True,Politics,5554.575
513,Equal Is Unfair: America's Misguided Fight Aga...,56.86,1,True,Politics,5998.730
514,Amid the Chaos,36.58,1,True,Cultural,3859.190
515,Dark Notes,19.19,5,True,Erotica,2024.545
516,The Long Shadow of Small Ghosts: Murder and Me...,10.97,1,True,Crime,1157.335

In [ ]:
df.shape

(517, 6)

#SQL-Table creation

In [ ]:
import sqlite3

In [ ]:
conn=sqlite3.connect("my_database.db")
Cursor=conn.cursor()

In [ ]:
Cursor.execute('''
CREATE TABLE categories(
category_id INTEGER PRIMARY KEY,
category_name TEXT UNIQUE);
''')
conn.commit()

In [ ]:
Cursor.execute('''
CREATE TABLE books(
book_id INTEGER PRIMARY KEY,
 title TEXT,
  price_gbp REAL,
   price_inr REAL,
    rating INTEGER,
     in_stock INTEGER,
      category_id INTEGER REFERENCES categories(category_id));
''')
conn.commit()

In [ ]:
categories=df['category'].unique()
categories

array(['Travel', 'Mystery', 'Historical Fiction', 'Sequential Art',
       'Classics', 'Philosophy', 'Romance', 'Womens Fiction', 'Fiction',
       'Childrens', 'Religion', 'Nonfiction', 'Music', 'Default',
       'Science Fiction', 'Sports and Games', 'Add a comment', 'Fantasy',
       'New Adult', 'Young Adult', 'Science', 'Poetry', 'Paranormal',
       'Art', 'Psychology', 'Autobiography', 'Parenting', 'Adult Fiction',
       'Humor', 'Horror', 'History', 'Food and Drink',
       'Christian Fiction', 'Business', 'Biography', 'Thriller',
       'Contemporary', 'Spirituality', 'Academic', 'Self Help',
       'Historical', 'Christian', 'Suspense', 'Short Stories', 'Novels',
       'Health', 'Politics', 'Cultural', 'Erotica', 'Crime'], dtype=object)

#Inserting values into tables
For loop to insert one category after the other

In [ ]:
for category in df["category"].unique():
    Cursor.execute(
        "INSERT INTO categories (category_name) VALUES (?)",
        (category,)
    )
conn.commit()

In [ ]:
pd.read_sql("SELECT * FROM categories",conn)

    category_id       category_name
0             1              Travel
1             2             Mystery
2             3  Historical Fiction
3             4      Sequential Art
4             5            Classics
5             6          Philosophy
6             7             Romance
7             8      Womens Fiction
8             9             Fiction
9            10           Childrens
10           11            Religion
11           12          Nonfiction
12           13               Music
13           14             Default
14           15     Science Fiction
15           16    Sports and Games
16           17       Add a comment
17           18             Fantasy
18           19           New Adult
19           20         Young Adult
20           21             Science
21           22              Poetry
22           23          Paranormal
23           24                 Art
24           25          Psychology
25           26       Autobiography
26           27           Parenting
27           28       Adult Fiction
28           29               Humor
29           30              Horror
30           31             History
31           32      Food and Drink
32           33   Christian Fiction
33           34            Business
34           35           Biography
35           36            Thriller
36           37        Contemporary
37           38        Spirituality
38           39            Academic
39           40           Self Help
40           41          Historical
41           42           Christian
42           43            Suspense
43           44       Short Stories
44           45              Novels
45           46              Health
46           47            Politics
47           48            Cultural
48           49             Erotica
49           50               Crime

In [ ]:
df

,title,price_gbp,rating,in_stock,category,price_inr
0,It's Only the Himalayas,45.17,2,True,Travel,4765.435
1,Full Moon over Noahâs Ark: An Odyssey to Mou...,49.43,4,True,Travel,5214.865
2,See America: A Celebration of Our National Par...,48.87,3,True,Travel,5155.785
3,Vagabonding: An Uncommon Guide to the Art of L...,36.94,2,True,Travel,3897.170
4,Under the Tuscan Sun,37.33,3,True,Travel,3938.315
...,...,...,...,...,...,...
512,Why the Right Went Wrong: Conservatism--From G...,52.65,4,True,Politics,5554.575
513,Equal Is Unfair: America's Misguided Fight Aga...,56.86,1,True,Politics,5998.730
514,Amid the Chaos,36.58,1,True,Cultural,3859.190
515,Dark Notes,19.19,5,True,Erotica,2024.545
516,The Long Shadow of Small Ghosts: Murder and Me...,10.97,1,True,Crime,1157.335

In [ ]:
pd.read_sql("SELECT * FROM books",conn)

Empty DataFrame
Columns: [book_id, title, price_gbp, price_inr, rating, in_stock, category_id]
Index: []

In [ ]:
Cursor.execute("SELECT category_id, category_name FROM categories")

category_map = {
    category_name: category_id
    for category_id, category_name in Cursor.fetchall()
}

In [ ]:
category_map

{'Travel': 1,
 'Mystery': 2,
 'Historical Fiction': 3,
 'Sequential Art': 4,
 'Classics': 5,
 'Philosophy': 6,
 'Romance': 7,
 'Womens Fiction': 8,
 'Fiction': 9,
 'Childrens': 10,
 'Religion': 11,
 'Nonfiction': 12,
 'Music': 13,
 'Default': 14,
 'Science Fiction': 15,
 'Sports and Games': 16,
 'Add a comment': 17,
 'Fantasy': 18,
 'New Adult': 19,
 'Young Adult': 20,
 'Science': 21,
 'Poetry': 22,
 'Paranormal': 23,
 'Art': 24,
 'Psychology': 25,
 'Autobiography': 26,
 'Parenting': 27,
 'Adult Fiction': 28,
 'Humor': 29,
 'Horror': 30,
 'History': 31,
 'Food and Drink': 32,
 'Christian Fiction': 33,
 'Business': 34,
 'Biography': 35,
 'Thriller': 36,
 'Contemporary': 37,
 'Spirituality': 38,
 'Academic': 39,
 'Self Help': 40,
 'Historical': 41,
 'Christian': 42,
 'Suspense': 43,
 'Short Stories': 44,
 'Novels': 45,
 'Health': 46,
 'Politics': 47,
 'Cultural': 48,
 'Erotica': 49,
 'Crime': 50}

used int(row["in_stock"]) so it returns as 1,0

In [ ]:
for _, row in df.iterrows():

    category_id = category_map[row["category"]]

    Cursor.execute(
        """
        INSERT INTO books
        (title, price_gbp, price_inr, rating, in_stock, category_id)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (row["title"],row["price_gbp"],row["price_inr"],row["rating"],int(row["in_stock"]),category_id)
    )

conn.commit()

#Insertion completed and starting queries

In [ ]:
#select all books whose category id is 1,5,7
query1=pd.read_sql("SELECT * FROM books WHERE category_id IN (1,5,7)",conn)   #1st query

In [ ]:
# select title and price in inr of books whose category id is 1 with hishest prices
query2=pd.read_sql("SELECT title,price_inr FROM books WHERE category_id = 1 ORDER BY price_inr DESC",conn)   #2nd query
query2

                                                title  price_inr
0                    A Year in Provence (Provence #1)   6000.840
1   Full Moon over Noahâs Ark: An Odyssey to Mou...   5214.865
2   See America: A Celebration of Our National Par...   5155.785
3                             It's Only the Himalayas   4765.435
4                                  A Summer In Europe   4677.870
5           Neither Here nor There: Travels in Europe   4109.225
6                                Under the Tuscan Sun   3938.315
7   Vagabonding: An Uncommon Guide to the Art of L...   3897.170
8                            The Great Railway Bazaar   3221.970
9                  1,000 Places to See Before You Die   2751.440
10  The Road to Little Dribbling: Adventures of an...   2448.655

In [ ]:
#select title and price in inr of 10 lowest priced books
query3=pd.read_sql("SELECT title,price_inr FROM books ORDER BY price_inr LIMIT 10",conn)   #3rd query

In [ ]:
#select all the books where the price in gbp is in between 20 and 40
query4=pd.read_sql("SELECT * from books WHERE price_gbp BETWEEN 20 AND 40",conn)       #4th query

In [ ]:
#select 20 unique category names from books on ascending order of category names
query5=pd.read_sql(
    """
    SELECT DISTINCT c.category_name
    FROM books AS b
    JOIN categories AS c
        ON b.category_id = c.category_id
    ORDER BY c.category_name
    LIMIT 20
    """,
    conn
)   #5th query

In [ ]:
#select 20 hishest prices books title,category name,prices in gbp,int and rating
query6=pd.read_sql(
    """
    SELECT
        b.title,
        c.category_name,
        b.price_gbp,
        b.price_inr,
        b.rating
    FROM books AS b
    INNER JOIN categories AS c
        ON b.category_id = c.category_id
    ORDER BY b.price_inr DESC
    LIMIT 20
    """,
    conn
)      #6th query
query6

,title,category_name,price_gbp,price_inr,rating
0,The Perfect Play (Play by Play #1),Romance,59.99,6328.945,3
1,Civilization and Its Discontents,Psychology,59.95,6324.725,2
2,The Bone Hunters (Lexy Vaughan & Steven Macaul...,Thriller,59.71,6299.405,3
3,Thomas Jefferson and the Tripoli Pirates: The ...,History,59.64,6292.020,1
4,Boar Island (Anna Pigeon #19),Mystery,59.48,6275.140,3
5,Life Without a Recipe,Autobiography,59.04,6228.720,5
6,Approval Junkie: Adventures in Caring Too Much,Autobiography,58.81,6204.455,5
7,Candide,Classics,58.63,6185.465,3
8,Catherine the Great: Portrait of a Woman,History,58.55,6177.025,4
9,Shameless,New Adult,58.35,6155.925,3
10,Silence in the Dark (Logan Point #4),Suspense,58.33,6153.815,3
11,Aristotle and Dante Discover the Secrets of th...,Young Adult,58.14,6133.770,4
12,The Death of Humanity: and the Case for Life,Philosophy,58.11,6130.605,4
13,The White Cat and the Monk: A Retelling of the...,Childrens,58.08,6127.440,4
14,The Stand,Horror,57.86,6104.230,2
15,Me Talk Pretty One Day,Autobiography,57.60,6076.800,2
16,The Bhagavad Gita,Religion,57.49,6065.195,3
17,I Had a Nice Time And Other Lies...: How to fi...,Womens Fiction,57.36,6051.480,4
18,Immunity: How Elie Metchnikoff Changed the Cou...,Science,57.36,6051.480,5
19,The Disappearing Spoon: And Other True Tales o...,Science,57.35,6050.425,5

In [ ]:
categories_df = pd.read_sql(
    "SELECT category_id, category_name FROM categories",
    conn
)

merge_result = pd.merge(
    df,
    categories_df,
    left_on="category",
    right_on="category_name",
    how="inner"
)

merge_result = merge_result[
    ["title", "category_name", "price_gbp", "price_inr", "rating"]
].sort_values(
    "price_inr",
    ascending=False
).head(20).reset_index(drop=True)
merge_result

,title,category_name,price_gbp,price_inr,rating
0,The Perfect Play (Play by Play #1),Romance,59.99,6328.945,3
1,Civilization and Its Discontents,Psychology,59.95,6324.725,2
2,The Bone Hunters (Lexy Vaughan & Steven Macaul...,Thriller,59.71,6299.405,3
3,Thomas Jefferson and the Tripoli Pirates: The ...,History,59.64,6292.020,1
4,Boar Island (Anna Pigeon #19),Mystery,59.48,6275.140,3
5,Life Without a Recipe,Autobiography,59.04,6228.720,5
6,Approval Junkie: Adventures in Caring Too Much,Autobiography,58.81,6204.455,5
7,Candide,Classics,58.63,6185.465,3
8,Catherine the Great: Portrait of a Woman,History,58.55,6177.025,4
9,Shameless,New Adult,58.35,6155.925,3
10,Silence in the Dark (Logan Point #4),Suspense,58.33,6153.815,3
11,Aristotle and Dante Discover the Secrets of th...,Young Adult,58.14,6133.770,4
12,The Death of Humanity: and the Case for Life,Philosophy,58.11,6130.605,4
13,The White Cat and the Monk: A Retelling of the...,Childrens,58.08,6127.440,4
14,The Stand,Horror,57.86,6104.230,2
15,Me Talk Pretty One Day,Autobiography,57.60,6076.800,2
16,The Bhagavad Gita,Religion,57.49,6065.195,3
17,I Had a Nice Time And Other Lies...: How to fi...,Womens Fiction,57.36,6051.480,4
18,Immunity: How Elie Metchnikoff Changed the Cou...,Science,57.36,6051.480,5
19,The Disappearing Spoon: And Other True Tales o...,Science,57.35,6050.425,5

In [ ]:
query6.equals(merge_result)

True

#Validation

In [ ]:
print("Number of books:", len(df))
print("Number of categories:", df["category"].nunique())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nRatings:")
print(sorted(df["rating"].unique()))

print("\nStock values:")
print(df["in_stock"].unique())

Number of books: 517
Number of categories: 50

Data types:
title         object
price_gbp    float64
rating         int64
in_stock        bool
category      object
price_inr    float64
dtype: object

Missing values:
title        0
price_gbp    0
rating       0
in_stock     0
category     0
price_inr    0
dtype: int64

Ratings:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

Stock values:
[ True]

In [ ]:
print("Books in database:")
display(pd.read_sql(
    "SELECT COUNT(*) AS book_count FROM books",
    conn
))

print("Categories in database:")
display(pd.read_sql(
    "SELECT COUNT(*) AS category_count FROM categories",
    conn
))

Books in database:

   book_count
0         517

Categories in database:

   category_count
0              50

In [ ]:
print("SQL JOIN result:")
display(query6)

print("Pandas merge result:")
display(merge_result)

print("Results match:", query6.equals(merge_result))

SQL JOIN result:

,title,category_name,price_gbp,price_inr,rating
0,The Perfect Play (Play by Play #1),Romance,59.99,6328.945,3
1,Civilization and Its Discontents,Psychology,59.95,6324.725,2
2,The Bone Hunters (Lexy Vaughan & Steven Macaul...,Thriller,59.71,6299.405,3
3,Thomas Jefferson and the Tripoli Pirates: The ...,History,59.64,6292.020,1
4,Boar Island (Anna Pigeon #19),Mystery,59.48,6275.140,3
5,Life Without a Recipe,Autobiography,59.04,6228.720,5
6,Approval Junkie: Adventures in Caring Too Much,Autobiography,58.81,6204.455,5
7,Candide,Classics,58.63,6185.465,3
8,Catherine the Great: Portrait of a Woman,History,58.55,6177.025,4
9,Shameless,New Adult,58.35,6155.925,3
10,Silence in the Dark (Logan Point #4),Suspense,58.33,6153.815,3
11,Aristotle and Dante Discover the Secrets of th...,Young Adult,58.14,6133.770,4
12,The Death of Humanity: and the Case for Life,Philosophy,58.11,6130.605,4
13,The White Cat and the Monk: A Retelling of the...,Childrens,58.08,6127.440,4
14,The Stand,Horror,57.86,6104.230,2
15,Me Talk Pretty One Day,Autobiography,57.60,6076.800,2
16,The Bhagavad Gita,Religion,57.49,6065.195,3
17,I Had a Nice Time And Other Lies...: How to fi...,Womens Fiction,57.36,6051.480,4
18,Immunity: How Elie Metchnikoff Changed the Cou...,Science,57.36,6051.480,5
19,The Disappearing Spoon: And Other True Tales o...,Science,57.35,6050.425,5

Pandas merge result:

,title,category_name,price_gbp,price_inr,rating
0,The Perfect Play (Play by Play #1),Romance,59.99,6328.945,3
1,Civilization and Its Discontents,Psychology,59.95,6324.725,2
2,The Bone Hunters (Lexy Vaughan & Steven Macaul...,Thriller,59.71,6299.405,3
3,Thomas Jefferson and the Tripoli Pirates: The ...,History,59.64,6292.020,1
4,Boar Island (Anna Pigeon #19),Mystery,59.48,6275.140,3
5,Life Without a Recipe,Autobiography,59.04,6228.720,5
6,Approval Junkie: Adventures in Caring Too Much,Autobiography,58.81,6204.455,5
7,Candide,Classics,58.63,6185.465,3
8,Catherine the Great: Portrait of a Woman,History,58.55,6177.025,4
9,Shameless,New Adult,58.35,6155.925,3
10,Silence in the Dark (Logan Point #4),Suspense,58.33,6153.815,3
11,Aristotle and Dante Discover the Secrets of th...,Young Adult,58.14,6133.770,4
12,The Death of Humanity: and the Case for Life,Philosophy,58.11,6130.605,4
13,The White Cat and the Monk: A Retelling of the...,Childrens,58.08,6127.440,4
14,The Stand,Horror,57.86,6104.230,2
15,Me Talk Pretty One Day,Autobiography,57.60,6076.800,2
16,The Bhagavad Gita,Religion,57.49,6065.195,3
17,I Had a Nice Time And Other Lies...: How to fi...,Womens Fiction,57.36,6051.480,4
18,Immunity: How Elie Metchnikoff Changed the Cou...,Science,57.36,6051.480,5
19,The Disappearing Spoon: And Other True Tales o...,Science,57.35,6050.425,5

Results match: True